---
version: '3'
networks:
# Data Center OpenNMS internal network
  net-onms:
    ipam:
      config:
        - subnet: 192.168.42.0/27
# Data Center management network
  net-mgmt-dc:
    ipam:
      config:
        - subnet: 192.168.42.32/27
# Location 01 management network
  net-mgmt-lo01:
    ipam:
      config:
        - subnet: 192.168.42.64/27
# Data Center BGP peering point-to-point links
  ptp-100-101:
    ipam:
      config:
        - subnet: 192.168.42.96/29
  ptp-108-109:
    ipam:
      config:
        - subnet: 192.168.42.104/29
  ptp-116-117:
    ipam:
      config:
        - subnet: 192.168.42.112/29
  ptp-124-125:
    ipam:
      config:
        - subnet: 192.168.42.120/29

volumes:
  data-cortex: {}
  data-postgres: {}
  data-opennms: {}
  data-grafana: {}

services:
  cortex:
    image: cortexproject/cortex:v1.15.3
    container_name: cortex
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "data-cortex:/cortex"
      - "./cortex/single-process-config-blocks-local.yaml:/etc/single-process-config-blocks-local.yaml"
    networks:
      net-onms:
        ipv4_address: 192.168.42.4
    command: [ "-config.file=/etc/single-process-config-blocks-local.yaml" ]

  database:
    image: timescale/timescaledb:latest-pg15
    hostname: database
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres -c 'max_connections=200'
    volumes:
      - data-postgres:/var/lib/postgresql/data:delegated
    networks:
      net-onms:
        ipv4_address: 192.168.42.8

  horizon:
    image: opennms/horizon:32.0.1
    hostname: horizon
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OPENNMS_DBNAME=opennms
      - OPENNMS_DBUSER=opennms
      - OPENNMS_DBPASS=opennms
      - OPENNMS_TIMESERIES_STRATEGY=integration
      - JAVA_OPTS=-Xmx4096m -XX:MaxMetaspaceSize=2048m
    networks:
      net-onms:
        ipv4_address: 192.168.42.16
    volumes:
      - ./horizon-overlay:/opt/opennms-overlay
    command: ["-s"]
    ports:
      - "8980:8980"
      - "8101:8101"
      - "61616:61616/tcp"

  grafana:
    image: docker.io/grafana/grafana:10.0.1
    depends_on:
      - horizon
    networks:
      net-onms:
        ipv4_address: 192.168.42.17
    environment:
      - TZ=${TIMEZONE:-America/New_York}
      - GF_INSTALL_PLUGINS=opennms-opennms-app,grafana-piechart-panel,neocat-cal-heatmap-panel,briangann-datatable-panel
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - data-grafana:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/

  sentinel-dc-12:
    image: opennms/sentinel:32.0.1
    environment:
      - TZ=Europe/Berlin
      - SENTINEL_ID=sentinel-dc-12
      - SENTINEL_LOCATION=sentinel
      - OPENNMS_BROKER_URL=tcp://horizon:61616
      - OPENNMS_HTTP_URL=http://horizon:8980/opennms
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opennms
      - JAVA_DEBUG_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
      - KARAF_DEBUG=true
    volumes:
      - ./sentinel-overlay:/opt/sentinel-etc-overlay
    networks:
      net-onms:
        ipv4_address: 192.168.42.12
    ports:
      - "8301:8301/tcp"
      - "5005:5005/tcp"

  minion-dc-20:
    image: opennms/minion:32.0.1
    environment:
      - TZ=Europe/Berlin
      - MINION_ID=minion-dc-20
      - MINION_LOCATION=data-center
      - OPENNMS_BROKER_URL=tcp://horizon:61616
      - OPENNMS_HTTP_URL=http://horizon:8980/opennms
    volumes:
      - ./minion-overlay/minion-dc-20:/opt/minion-etc-overlay
    networks:
      net-onms:
        ipv4_address: 192.168.42.20
      net-mgmt-dc:
        ipv4_address: 192.168.42.36
    ports:
      - "8201:8201/tcp"

  minion-lo01-24:
    image: opennms/minion:32.0.1
    environment:
      - TZ=Europe/Berlin
      - MINION_ID=minion-lo01-24
      - MINION_LOCATION=location-01
      - OPENNMS_BROKER_URL=tcp://horizon:61616
      - OPENNMS_HTTP_URL=http://horizon:8980/opennms
    volumes:
      - ./minion-overlay/minion-lo01-24:/opt/minion-etc-overlay
    networks:
      net-onms:
        ipv4_address: 192.168.42.24
      net-mgmt-lo01:
        ipv4_address: 192.168.42.68
    ports:
      - "8202:8201/tcp"

  ### BGP Router in Data Center
  rt-dc-37:
    image: quay.io/labmonkeys/gobgp:3.16.0.b1914
    environment:
      - TZ=Europe/Berlin
    volumes: 
      - ./rt-dc-37/gobgpd.conf:/gobgpd.conf
    networks:
      net-mgmt-dc:
        ipv4_address: 192.168.42.37
      ptp-100-101:
        ipv4_address: 192.168.42.100
      ptp-108-109:
        ipv4_address: 192.168.42.108
    command: ["-f", "/gobgpd.conf"]

  rt-dc-38:
    image: quay.io/labmonkeys/gobgp:3.16.0.b1914
    environment:
      - TZ=Europe/Berlin
    volumes: 
      - ./rt-dc-38/gobgpd.conf:/gobgpd.conf
    networks:
      net-mgmt-dc:
        ipv4_address: 192.168.42.38
      ptp-100-101:
        ipv4_address: 192.168.42.101

    command: ["-f", "/gobgpd.conf"]

  rt-dc-39:
    image: quay.io/labmonkeys/gobgp:3.16.0.b1914
    environment:
      - TZ=Europe/Berlin
    volumes: 
      - ./rt-dc-39/gobgpd.conf:/gobgpd.conf
    networks:
      net-mgmt-dc:
        ipv4_address: 192.168.42.39
      ptp-108-109:
        ipv4_address: 192.168.42.109
    command: ["-f", "/gobgpd.conf"]

### BGP Router in location 01
  rt-lo01-69:
    image: quay.io/labmonkeys/gobgp:3.16.0.b1914
    environment:
      - TZ=Europe/Berlin
    volumes: 
      - ./rt-lo01-69/gobgpd.conf:/gobgpd.conf
    networks:
      net-mgmt-lo01:
        ipv4_address: 192.168.42.69
      ptp-116-117:
        ipv4_address: 192.168.42.116
      ptp-124-125:
        ipv4_address: 192.168.42.124
    command: ["-f", "/gobgpd.conf"]

  rt-lo01-70:
    image: quay.io/labmonkeys/gobgp:3.16.0.b1914
    environment:
      - TZ=Europe/Berlin
    volumes: 
      - ./rt-lo01-70/gobgpd.conf:/gobgpd.conf
    networks:
      net-mgmt-lo01:
        ipv4_address: 192.168.42.70
      ptp-116-117:
        ipv4_address: 192.168.42.117
    command: ["-f", "/gobgpd.conf"]

  rt-lo01-71:
    image: quay.io/labmonkeys/gobgp:3.16.0.b1914
    environment:
      - TZ=Europe/Berlin
    volumes: 
      - ./rt-lo01-71/gobgpd.conf:/gobgpd.conf
    networks:
      net-mgmt-lo01:
        ipv4_address: 192.168.42.71
      ptp-124-125:
        ipv4_address: 192.168.42.125
    command: ["-f", "/gobgpd.conf"]
