{
 "title": "BGP & Alarms",
 "time": { "from": "now-1d", "to": "now+1h" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Alarms & situations (noack)",
   "type": "opennms-helm-alarm-table-panel",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "entityType": { "id": "alarm", "label": "Alarms", "queryFunction": "alarms" },
     "filter": {
      "clauses": [
       {
        "operator": { "id": 1, "label": "AND" },
        "restriction": { "attribute": "isAcknowledged", "comparator": { "id": 1, "label": "EQ" }, "value": "false" }
       },
       {
        "operator": { "id": 1, "label": "AND" },
        "restriction": {
         "clauses": [
          {
           "operator": { "id": 1, "label": "AND" },
           "restriction": { "attribute": "isSituation", "comparator": { "id": 1, "label": "EQ" }, "value": "true" }
          },
          {
           "operator": { "id": 2, "label": "OR" },
           "restriction": { "attribute": "isInSituation", "comparator": { "id": 1, "label": "EQ" }, "value": "false" }
          }
         ]
        }
       },
       {
        "operator": { "id": 1, "label": "AND" },
        "restriction": { "attribute": "severity", "comparator": { "id": 5, "label": "GT" }, "value": "NORMAL" }
       }
      ],
      "limit": 0,
      "orderBy": []
     }
    }
   ]
  },
  {
   "title": "BMP (p95)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "attribute": "Dispatch95",
     "label": "Latency",
     "nodeId": "selfmonitor:2",
     "resourceId": "sinkProducerMetrics[Telemetry-BMP]",
     "type": "attribute"
    }
   ]
  },
  {
   "title": "Alarmd Facts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "math:ceil(facts_decimal)", "label": "facts", "type": "expression" }
   ]
  },
  {
   "title": "Alarmd Liveness (p95)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "attribute": "DroolsAlarmdLv95",
     "label": "Liveness",
     "nodeId": "selfmonitor:2",
     "resourceId": "interfaceSnmp[opennms-jvm]",
     "type": "attribute"
    }
   ]
  },
  {
   "title": "Peer Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": " SELECT\n    max(RouterName) as \"RouterName\",\n    max(PeerName) as \"PeerName\",\n    max(PeerIP) as \"PeerIP\",\n    max(PeerASN) as \"PeerASN\",\n    max(peer_state) as \"State\",\n    max(LastModified) as \"LastModified\"\nFROM bmp_v_peers p\n  LEFT JOIN bmp_stats_peer_rib s ON (p.peer_hash_id = s.peer_hash_id\n          AND s.interval_time >= now() - interval '20 minutes')\nGROUP BY p.peer_hash_id;"
    }
   ]
  },
  {
   "title": "Situations",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "entityType": { "id": "alarm", "label": "Alarms", "queryFunction": "alarms" },
     "filter": {
      "clauses": [
       {
        "operator": { "id": 1, "label": "AND" },
        "restriction": { "attribute": "isSituation", "comparator": { "id": 1, "label": "EQ" }, "value": "true" }
       },
       {
        "operator": { "id": 1, "label": "AND" },
        "restriction": { "attribute": "severity", "comparator": { "id": 7, "label": "GE" }, "value": "WARNING" }
       }
      ],
      "limit": 0,
      "orderBy": []
     }
    }
   ]
  },
  {
   "title": "Prefix History",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": " select event,routername,peername,prefix,origin_as,as_path,lastmodified\n    from bmp_v_ip_routes_history \n    where  $__timeFilter(lastmodified)\n    order by lastmodified desc,id desc\n    limit 1000;"
    }
   ]
  }
 ]
}