{
 "title": "Looking Glass",
 "time": { "from": "now-7d", "to": "now+7d" },
 "templating": {
  "list": [
   { "name": "prefix", "label": "Prefix", "query": "10.38.0.0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Looking Glass\n\n> Enter an IP address with or without bit length.  The longest matched prefix will be used. Specify the length to find exact match or best aggregate."
   }
  },
  {
   "title": "ASN Info",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select distinct origin_as,i.as_name,org_id,org_name,remarks,address,city,state_prov,country,raw_output,source\n  from bmp_ip_ribs r LEFT JOIN  bmp_asn_info i ON (i.asn = r.origin_as)\n  where r.prefix = (select prefix from bmp_ip_ribs where inet(prefix) >>= '[[prefix]]' order by prefix desc limit 1) \n    and origin_as > 0\n"
    }
   ]
  },
  {
   "title": "Router Visibility",
   "type": "piechart",
   "description": "Prefix found in router's RIB.",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(r.last_updated))) as time,\n  CASE WHEN v.router_hash_id is null THEN 'Not in Router RIB' ELSE 'In Router Rib' END as metric,\n  1 as value\nFROM bmp_routers r\n  left join (select distinct router_hash_id\n             from bmp_v_ip_routes \n             where prefix = (select prefix from bmp_ip_ribs where inet(prefix) >>= '[[prefix]]' order by prefix_len desc limit 1)\n                and is_withdrawn = false group by router_hash_id) v \n            on (r.hash_id = v.router_hash_id)\nWHERE r.state = 'UP'\nGROUP BY r.hash_id,v.router_hash_id\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Peer Visibility",
   "type": "piechart",
   "description": "Prefix found in peer RIB's",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(p.last_updated))) as time,\n  CASE WHEN v.peer_hash_id is null THEN 'Not in Peers RIB' ELSE 'In Peer RIB' END as metric,\n  1 as value\nFROM bmp_peers p\n  left join (select peer_hash_id,isPeerIPv4\n             from bmp_v_ip_routes \n             where prefix = (select prefix from bmp_ip_ribs where inet(prefix) >>= '[[prefix]]' order by prefix_len desc limit 1)\n                and is_withdrawn = false group by peer_hash_id,ispeeripv4) v \n            on (p.hash_id = v.peer_hash_id)\nWHERE p.is_ipv4 = CASE WHEN family(inet('[[prefix]]')) = 4 THEN true ELSE false END\n  AND p.state = 'UP'\nGROUP BY p.hash_id,v.peer_hash_id\nORDER BY time"
    }
   ]
  },
  {
   "title": "Prefix Info",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select distinct r.origin_as as recv_origin_as,\n    CASE WHEN g.rpki_origin_as is null THEN 0 ELSE g.rpki_origin_as END as rpki_origin_as,\n    CASE WHEN i.origin_as is null THEN 0 ELSE i.origin_as END as irr_origin_as,\n    i.descr,i.source\n  from bmp_ip_ribs r \n    LEFT JOIN bmp_route_info i ON (i.prefix = r.prefix)\n    LEFT JOIN bmp_global_ip_ribs g ON (g.prefix = r.prefix)\n  where r.prefix = (select prefix from bmp_ip_ribs where inet(prefix) >>= '[[prefix]]' order by prefix desc limit 1)\n    and r.origin_as > 0\n"
    }
   ]
  },
  {
   "title": "Looking Glass",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": " select lastmodified,routername,peername,prefix,prefixlen,\n        origin_as,med,localpref,as_path,communities \n    from bmp_v_ip_routes \n    where prefix = (select prefix from bmp_ip_ribs where inet(prefix) >>= '[[prefix]]' order by prefix_len desc limit 1)\n      AND is_withdrawn = false\n      \n    order by routername,peername \n    limit 2000;"
    }
   ]
  }
 ]
}